"""empty message

Revision ID: 44709639b221
Revises: 623324d3d3f8
Create Date: 2020-03-12 11:52:53.086060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44709639b221'
down_revision = '623324d3d3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.drop_column('message', 'sender_id')
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_message_read_time')
    op.add_column('message', sa.Column('sender_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    # ### end Alembic commands ###
