"""empty message

Revision ID: 4ca4a767b134
Revises: 3fb6e4e5072e
Create Date: 2020-02-27 13:47:49.691330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca4a767b134'
down_revision = '3fb6e4e5072e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likers', type_='foreignkey')
    op.drop_constraint(None, 'likers', type_='foreignkey')
    op.create_foreign_key(None, 'likers', 'post', ['liker_id'], ['id'])
    op.create_foreign_key(None, 'likers', 'post', ['liked_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likers', type_='foreignkey')
    op.drop_constraint(None, 'likers', type_='foreignkey')
    op.create_foreign_key(None, 'likers', 'user', ['liked_id'], ['id'])
    op.create_foreign_key(None, 'likers', 'user', ['liker_id'], ['id'])
    # ### end Alembic commands ###
