"""empty message

Revision ID: 623324d3d3f8
Revises: e5361df8ac1c
Create Date: 2020-03-12 11:51:11.334112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623324d3d3f8'
down_revision = 'e5361df8ac1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    op.drop_column('message', 'user_id')
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_message_read_time')
    op.add_column('message', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    # ### end Alembic commands ###
