"""Added message field

Revision ID: 70cdf3f60687
Revises: f6c0322fd43f
Create Date: 2020-03-11 13:11:09.306299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cdf3f60687'
down_revision = 'f6c0322fd43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('body', sa.String(length=1028), nullable=True))
    op.add_column('message', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_column('message', 'user_id')
    op.drop_column('message', 'timestamp')
    op.drop_column('message', 'body')
    # ### end Alembic commands ###
