"""Added messages

Revision ID: 8d8b8d7780ae
Revises: 97cb4bfef448
Create Date: 2020-03-12 12:02:59.796526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8b8d7780ae'
down_revision = '97cb4bfef448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_message_read_time')
    # ### end Alembic commands ###
