"""empty message

Revision ID: e5361df8ac1c
Revises: 70cdf3f60687
Create Date: 2020-03-12 11:43:49.479490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5361df8ac1c'
down_revision = '70cdf3f60687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    op.drop_column('message', 'user_id')
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_message_read_time')
    op.add_column('message', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'sender_id')
    op.drop_column('message', 'receiver_id')
    # ### end Alembic commands ###
