"""empty message

Revision ID: f6c0322fd43f
Revises: f55574a54a24
Create Date: 2020-03-06 12:41:00.693070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c0322fd43f'
down_revision = 'f55574a54a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_set', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_set')
    # ### end Alembic commands ###
